version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/blogdb
    command: sleep infinity  # Flaskは手動で起動するためコンテナは待機状態

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
